dist: trusty
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
  - secure: RRjYhwK+hOJqBCA+Y3ruFQRTZpp2RKcktNQ/iY5GK4z4PPzbnNlHTnpPMl5P8vxNKtyfd9tHFtcdHxXKG+2mbWIehxHiAgE41zBcjpp/TVj5YPGQklor9Tt96G+aknXEBCBq/DW9bICeCmbkfyiRj54euHdXqdVtScAMFGoVNYD2iCpol5VsSc5oxwyHNOSGbQDIm+lCOQ+SGsfj/3qWB8WCXYdfOWee4WlcdKXBATAWKbIANf5DvcPyB9Cbg3cbyCPKzyMjeVkpFs8Z5WJCDj2PE6oVw0GPlg1plX97PzCdJNNJXtrK0gwNRbxYLluYoIfT8banUOtBcnXnRHX8Ff6+HIbm7OuDo4mLE0W42G3nLdEIBU/L4yFJnLV8ukqVVcKaMd+C2r8/gKqcYxGghlq8Bxt5OcOUc+ENfoDx2ExVrnb5toAZQ0Iqwg4nD36/Kc2pw/AmOVJvyIuIctzwoHsGiZ+e+QZF4qEkocFi7xsGNXQcDYHkacZBnbHVyQZ4EEd3WOd5Uw3v8j3TdZNn8eAwuj4862os7VpZg5239Xd8f8zocuOBL77ujhhdkrIY+DBtX+qHBLul8nZgaTHjEDkzy4LUAZzDJPdeObimdl06K243T/GFY518mSVCHoSbmMORrJgNcu6YPOrlKBcEBEETTWemfiCD4X1hqIrqF70=
  - secure: WjxKJOc8F9UNME6Qus+HO3g7eCdKwDqufjLHpyxFoWNHWFp1k7YNwc/fTStWsrjV8+ogPXTC1zx8rW9KS/OVU8X1uTJ50Cd2x5bZY8ABdo8pCzf2A/cXl8sy1aLyADg8cndbpRWnMTVeTomCjbkSe/sZQRuEdOCEQYJ9eNblWyc+O8hqBw3HMAM6tP9E83EPsjgTVCdfCHBRNEMNSU4/yPOHX8YOxOjWnMqciOH/MPn+pmU8BG4jwpFIUnsXfihgrXoBztDCJJ4fT0LQwHSL6I878/M4NxOU5m712iDVuGDL/A+9XdzvFgvwyI/dOwJmUKe1P+g2bQ/dkuXrwv61DKYyOF5M4GKCyHlXjh6E7dLl+Y2P+Ozko4R8oCaD6ggkEXMs+HLX/WDENFOi5BP8XFYvS2AIcYiWv3SOMZw6wMZ8cH14fkY/DUSMAXAoN130rCWGrP5bSUAu9ieFucS6xmVnwBNZj8aZbc30i2uYRtt9JFz5DSPEtNohNomBxu4cHExTkNuiWKixd7g6hJlqpSsRRqle1ExeRchlzsp90KopmiWec1dL/Z9LZsTFKSF3aY/4alZAG62IxgnezgqHldfd2T2PGQv+q5AWH57Fx2Sa1QUuRvwzKs/iQldryAKZUXw8AtzJb9tNxwwSfY1w6M9J4XRnZSuCcIkXcPO0LDY=
  - secure: Oyy3K6FH7fJIonFsRvXXJessz6jZ/eutsY6eS3+qph63YezBcPvv7EIisg8acqJ/PZX4lKwUtPZEOzgKYFfJsSu3iWinEdVxUBNYtuDHAbnmiWdB6ApT6nL+HJ9xDvE40+p0JDQCgr+WS8RyWrDrMI6nOfxRlwbcBI6fh104s8WzBbI7goAAGIXR21U/PXqkQZpEYjHxMDexNDETRBo3Rt/41TriLfu248I2veJFPHoVhAFT7mDBLtCm7Mq7YRfIzyJlB62ESz/s7SAKoAuq3+Z4fxYA+2k+YdsGptgzOo4DbLDCCLEgp3FjSM5UK6spYvgvmaOn14EeEKYcteBMW57BqOcw+3CT60Qz2MXGoYqD5Tb6DIgxDvjVepKuXyX7ZkiVBDNqJ+VDhsYJOzZPIY9pXMSRxVSuCeIskxd3j4+HyONZWRnzFkwi8zvzmb0Fql2Fec5hmot+cK7wiqOqYu3Fw088YT95nG6o5ehVqrF3h6z0FG/iQmAoPq2cG7PKmRZH+fYMndajmvJT7Fd0bYH9IVtd+LEPkryCWewH2S6WjBacIj1gX6MkkFUzkake7sCjrnkEDPwvoenIM/Vf0Ry5RBf88E7DVTYQYGvm3TXqCX+jkv//eEcFK33vciV1a2d1XesY0m97JyqVoU4VM+SYvXFjnmHYgmZ6Szx4LPo=
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
